--// simple anti env log - check function, global valid
if io or string.dump or not game or not game.GetService or not game.HttpService or not game.CoreGui or not getgenv or not tick or not wait or not task or not task.wait or game.HttpService:JSONEncode({["hello"]="world"}) ~= "{\"hello\":\"world\"}" or game.HttpService:JSONDecode("{\"hello\":\"world\"}")["hello"] ~= "world" or not newcclosure or not typeof or not clonefunction then
    while wait() do
        _G.helloworld = function()
            local aa = "qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM1234567890-=[];'\\,./\"`"
            local a = ""
            for i=1,math.floor(((36 * 67) / 367) * 3) do
                local gg = math.random(1,#aa)
                a = a .. aa:sub(gg,gg)
            end
            return a
        end
        _G["yeuu thi"] = function ()
            local aa = "qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM"
            local a = ""
            for i=1,36 do
                local gg = math.random(1,#aa)
                a = a .. aa:sub(gg,gg)
            end
            return a
        end
        _G["to yeu cac cau rat nhieuuuu"] = function ()
            _G["xnxx"] = "🙂😀😄😆😂😅🤣😊☺️😌😉😏😍😘😗😙😚🤗😳🙃😇😈😛😝😜😋🤤🤓😎🤑😒🙁☹️😞😔😖😓😢😢😭😟😣😩😫😕🤔🙄😤😠😡😶🤐😐😑😯😲😨😧😰😱😪😴😬🤥🤧🤒😷🤕😵🤢🤠🤡👿👹👺👻💀👽👾🤖💩🎃"
            local a = ""
            for i=1,36 do
                local gg = math.random(1,#_G["xnxx"])
                a = a .. _G["xnxx"]:sub(gg,gg)
            end
            return a
        end
        local uayyy = _G["to yeu cac cau rat nhieuuuu"]()
        local bien = "local "
        local gl = function ()
            local gll = {"getgenv()", "_G", "getfenv(0)"}
            return gll[math.random(1,#gll)]
        end
        local str = '"%s"'
        local tb = "{\n%s\n}"
        local func = "function()\n%s\nend"
        function gencode()
            local code = "-- this source code generated by @noguchi.hyuga / @noguchi.hyuga was here\n"
            for i=1,36 + 67 do
                code = code .. bien .. _G["yeuu thi"]() .. " = " .. (function ()
                    local hmm = math.random(1,4)
                    if hmm == 1 then
                        return tostring(36 ^ math.random(36,67))
                    elseif hmm == 2 then
                        return string.format(func, (function ()
                            return string.format("\nlocal %s = \"%s\"\n\treturn 36 ^ 67", _G["yeuu thi"](), _G["to yeu cac cau rat nhieuuuu"]())
                        end)())
                    elseif hmm == 3 then
                        return string.format(str, _G["to yeu cac cau rat nhieuuuu"]())
                    else
                        return string.format(tb, (function ()
                            local ahihi = ""
                            for i=1,255 do
                                ahihi = ahihi .. string.format("[%d] = '%d',", i, math.random(1,255))
                            end
                            for i=36,67 do
                                ahihi = ahihi .. string.format("['%s'] = '%s',",_G.helloworld(), _G["to yeu cac cau rat nhieuuuu"]())
                            end
                            return ahihi .. "\n"
                        end)())
                    end
                end)() .. "\n" .. gl() .. string.format("['%s'] = '%s'", _G.helloworld(), _G["to yeu cac cau rat nhieuuuu"]()) .. "\n"
            end
            return code
        end
        local abc = gencode() .. gencode()
        local info = debug.getinfo(1, "S")
        print(info.source)
        if info and info.source then
            print(info.source)
            if info.source:sub(1,1) == "@" then
                pcall(function ()
                    local fn = info.source:sub(2)
                    local fl = io.open("deobfuscated_" .. fn .. ".lua", "w")
                    fl:write(abc)
                    fl:close()
                end)
                pcall(function ()
                    local bc = string.dump(function ()
                        local gc = gencode()
                        local hw = _G.helloworld
                        local yt = _G["yeuu thi"]
                        local _1,_2,_3,_4,_5,_6,_7,_8,_9,_10 = (function ()
                            local ngu = {2134,312321,213321,213321321,312312,312132,3,43254,432,3246754,32412,12376,54312}
                            return (unpack or table.unpack)(ngu)
                        end)()
                        return gc,hw,yt, _1,_2,_3,_4,_5,_6,_7,_8,_9,_10 .. (function()
                            return function()
                                return function()
                                    return 36
                                end
                            end
                        end)()
                    end)
                    local fc = io.open("deobfuscated_" .. fn .. ".luac", "w")
                    fc:write(bc)
                    fc:close()
                end)
            end
        end
        hellochat = _G.helloworld()
        _G[_G.helloworld()] = {
            _G.helloworld(),
            _G.helloworld(),
            [36] = {
                _G.helloworld(),
                [_G.helloworld()] = _G.helloworld(), [67] = {
                    _G.helloworld(), _G.helloworld()
                }
            }
        }
        _G["hello_"..hellochat] = {}
        _G["hello_"..hellochat][100000] = {}
        _G["hello_"..hellochat][100000][100036] = {}
        _G["hello_"..hellochat][100000][100036][367763] = {
            function (...)
                xx = 0
                while xx <= 36 do
                    xx = xx - 36
                    xx = xx + 67
                end
                return (function (...)
                    return function ()
                        _G["hello_skid_"..hellochat] = {}
                        _G["hello_skid_"..hellochat][100000] = {}
                        _G["hello_skid_"..hellochat][100000][100036] = {}
                        _G["hello_skid_"..hellochat][100000][100036][367763] = {}
                        return _G["hello_skid_"..hellochat]
                    end
                end)(...)
            end
        }
        getgenv()[_G.helloworld()] = function ()
            _G[_G.helloworld()] = (_G.helloworld())
            return _G[_G.helloworld()], _G.helloworld(), _G.helloworld()
        end
        local uv = {_G.helloworld()}
        local gg
        _G[_G.helloworld()] = function ()
            gg = _G[_G.helloworld()]
            getgenv()[string.reverse((string.reverse(gg) .. string.reverse(_G.helloworld())))] = function ()
                print("Script is running")
                return "hello skid"
            end
            return "okia"
        end
        
        helloskid = {
            "Berry",
            "FullMoon",
            "DoughKing",
            "RipIndra",
            "WinterSky",
            "PureRed",
            "ApiStatus",
            "Mirage",
            "Prehistoric",
            "Elite",
            "CursedCaptain",
            "Darkbeard",
            "Graybeard",
            "Oroshi",
            "Saishi",
            "Shizu"
        }
        _G["chiu cac cau mat roiiii"] = function ()
            return string.format("https://%d.%d.%d.%d:3667/", math.random(1,255),math.random(1,255),math.random(1,255))
        end
        _G["cac cau log env cua to lam gi vayyy"] = function ()
            return helloskid[math.random(1, #helloskid)]
        end
        _G.Response = game:HttpGet(_G["chiu cac cau mat roiiii"]().._G["cac cau log env cua to lam gi vayyy"]())
        pcall(function ()
            _G.Data = game.HttpService:JSONDecode(_G.Response)
        end)
    end
end

-- function no(...)
--     return ...
-- end

function no(...)
    print((unpack or table.unpack)({...}))
end

local abc = 36
local cba = 67
function strreverse(str)
    local new = {}
    for i=#str,1,-1 do
        new[#new + 1] = str:sub(i,i)
    end
    return table.concat(new)
end
no("abc:",abc,"cba:",cba)
no("abc > cba:", abc > cba)
no("abc < cba:", abc < cba)
local str = "con me may beo"
no("str:", str)
no("reverse:", strreverse(str))
no("cai dit con mayyyyyyyyyyyyyyyyyyyyyyyyyyyyy")
local xx = {}
function xx:helloworld()
    return [==[Năm mới chúc bạn luôn tràn đầy năng lượng, nhiệt huyết và một trái tim ấm áp. Dù cuộc sống có đôi lúc khó khăn và thử thách, hãy nhớ rằng đó là những bước ngoặt giúp bạn trưởng thành hơn, mạnh mẽ hơn. Mỗi khó khăn là một cơ hội để bạn học hỏi, mỗi thất bại là một bài học quý giá. Chắc chắn rằng bạn sẽ vươn lên và đạt được tất cả những gì bạn mong muốn, vì bạn có sức mạnh, sự kiên nhẫn và quyết tâm không ngừng nghỉ. Mong rằng bạn sẽ luôn giữ được sự lạc quan, biết ơn những điều tốt đẹp xung quanh mình và nhìn nhận mọi khó khăn với thái độ tích cực. Đừng bao giờ quên rằng bạn xứng đáng với những điều tốt đẹp, những niềm vui và thành công, trong cuộc sống này. Hãy tiếp tục bước đi, vì mỗi bước đi dù nhỏ cũng là một phần trong hành trình tuyệt vời của bạn.
Chúc bạn luôn biết yêu thương và trân trọng bản thân, vì bạn là người duy nhất có thể tạo ra những thay đổi trong cuộc sống của mình. Đừng ngừng mơ ước, và hãy luôn dâng ước mơ lớn, vì không có gì là không thể nếu bạn kiên trì và quyết tâm. Cuộc sống này rộng lớn và đây cơ hội, và bạn sẽ tìm thấy con đường của mình khi bạn không ngừng tìm kiếm và cố gắng. Hãy nhớ rằng không có giới hạn nào đối với khả năng của bạn, chỉ có bạn mới có thể quyết định sức mạnh tiềm ẩn trong mình. Mỗi ngày là một cơ hội mới để bạn phát triển và vươn lên. Đừng sợ thay đổi, vì chính sự thay đổi sẽ mang đến cho bạn những cơ hội và trải nghiệm mới. Đừng lo lắng về những thất bại, vì mỗi làn thất bại chỉ là một bước đệm để bạn đạt được thành công lớn hơn. Chúc bạn luôn được bao quanh bởi tình yêu, sự hỗ trợ và những mối quan hệ ý nghĩa.
Những người xung quanh bạn chính là nguồn động lực giúp bạn tiếp tục bước đi trên con đường của mình. Hãy luôn biết ơn và trân trọng những mối quan hệ này, vì chúng sẽ là những kho báu trong cuộc sống của bạn. Mong rằng bạn sẽ không bao giờ từ bỏ ước mơ, dù cho con đường có gập ghềnh, dù có những lúc cảm thấy mệt mỏi. Hãy nhớ rằng những ước mơ lớn cần thời gian để thành hiện thực, và với mỗi bước đi, bạn sẽ đến gần hơn với mục tiêu của mình.
Đừng ngừng tiến về phía trước, vì bạn xứng đáng có được tất cả những điều tuyệt vời nhất. Happy new year 2026 🥳💓💓]==]
end
function xx:gg()
    return 1 > 1 or 2 > 2 or 36 > 67
end
if not xx:gg() then
    no(xx:helloworld())
end
